run:
	docker-compose -f ${PWD}/docker-compose.yml up -d

stop:
	docker-compose -f ${PWD}/docker-compose.yml stop

down:
	docker-compose -f ${PWD}/docker-compose.yml down

re-build:
	docker-compose -f ${PWD}/docker-compose.yml up -d --build
	